/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'role' : IDL.Text,
});
export const UserProfileEntry = IDL.Record({
  'principal' : IDL.Principal,
  'profile' : UserProfile,
});
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdBy' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'authorName' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const Comment = IDL.Record({
  'content' : IDL.Text,
  'authorName' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const Doubt = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'authorName' : IDL.Text,
  'author' : IDL.Principal,
  'subjectTag' : IDL.Text,
  'timestamp' : IDL.Int,
  'comments' : IDL.Vec(Comment),
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'eventDate' : IDL.Int,
});
export const Stats = IDL.Record({
  'eventCount' : IDL.Nat,
  'doubtCount' : IDL.Nat,
  'userCount' : IDL.Nat,
  'announcementCount' : IDL.Nat,
  'studyPostCount' : IDL.Nat,
});
export const StudyPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'authorName' : IDL.Text,
  'author' : IDL.Principal,
  'likes' : IDL.Vec(IDL.Principal),
  'subjectTag' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createDoubt' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createEvent' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [], []),
  'createStudyPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'deleteDoubt' : IDL.Func([IDL.Nat], [], []),
  'deleteStudyPost' : IDL.Func([IDL.Nat], [], []),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfileEntry)], ['query']),
  'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getDoubts' : IDL.Func([], [IDL.Vec(Doubt)], ['query']),
  'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getStudyPosts' : IDL.Func([], [IDL.Vec(StudyPost)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeStudyPost' : IDL.Func([IDL.Nat], [], []),
  'registerUser' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendChatMessage' : IDL.Func([IDL.Text], [], []),
  'updateDoubt' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'role' : IDL.Text,
  });
  const UserProfileEntry = IDL.Record({
    'principal' : IDL.Principal,
    'profile' : UserProfile,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdBy' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'authorName' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const Comment = IDL.Record({
    'content' : IDL.Text,
    'authorName' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const Doubt = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'authorName' : IDL.Text,
    'author' : IDL.Principal,
    'subjectTag' : IDL.Text,
    'timestamp' : IDL.Int,
    'comments' : IDL.Vec(Comment),
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'eventDate' : IDL.Int,
  });
  const Stats = IDL.Record({
    'eventCount' : IDL.Nat,
    'doubtCount' : IDL.Nat,
    'userCount' : IDL.Nat,
    'announcementCount' : IDL.Nat,
    'studyPostCount' : IDL.Nat,
  });
  const StudyPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'authorName' : IDL.Text,
    'author' : IDL.Principal,
    'likes' : IDL.Vec(IDL.Principal),
    'subjectTag' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createDoubt' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createEvent' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [], []),
    'createStudyPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'deleteDoubt' : IDL.Func([IDL.Nat], [], []),
    'deleteStudyPost' : IDL.Func([IDL.Nat], [], []),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfileEntry)], ['query']),
    'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getDoubts' : IDL.Func([], [IDL.Vec(Doubt)], ['query']),
    'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getStudyPosts' : IDL.Func([], [IDL.Vec(StudyPost)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeStudyPost' : IDL.Func([IDL.Nat], [], []),
    'registerUser' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendChatMessage' : IDL.Func([IDL.Text], [], []),
    'updateDoubt' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };