/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'createdBy' : Principal,
  'timestamp' : bigint,
}
export interface ChatMessage {
  'id' : bigint,
  'content' : string,
  'authorName' : string,
  'author' : Principal,
  'timestamp' : bigint,
}
export interface Comment {
  'content' : string,
  'authorName' : string,
  'author' : Principal,
  'timestamp' : bigint,
}
export interface Doubt {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'authorName' : string,
  'author' : Principal,
  'subjectTag' : string,
  'timestamp' : bigint,
  'comments' : Array<Comment>,
}
export interface Event {
  'id' : bigint,
  'title' : string,
  'createdBy' : Principal,
  'description' : string,
  'timestamp' : bigint,
  'eventDate' : bigint,
}
export interface Stats {
  'eventCount' : bigint,
  'doubtCount' : bigint,
  'userCount' : bigint,
  'announcementCount' : bigint,
  'studyPostCount' : bigint,
}
export interface StudyPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'authorName' : string,
  'author' : Principal,
  'likes' : Array<Principal>,
  'subjectTag' : string,
  'timestamp' : bigint,
}
export interface UserProfile {
  'bio' : string,
  'displayName' : string,
  'role' : string,
}
export interface UserProfileEntry {
  'principal' : Principal,
  'profile' : UserProfile,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAnnouncement' : ActorMethod<[string, string], undefined>,
  'createDoubt' : ActorMethod<[string, string, string], undefined>,
  'createEvent' : ActorMethod<[string, string, bigint], undefined>,
  'createStudyPost' : ActorMethod<[string, string, string], undefined>,
  'deleteDoubt' : ActorMethod<[bigint], undefined>,
  'deleteStudyPost' : ActorMethod<[bigint], undefined>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfileEntry>>,
  'getAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getDoubts' : ActorMethod<[], Array<Doubt>>,
  'getEvents' : ActorMethod<[], Array<Event>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getStats' : ActorMethod<[], Stats>,
  'getStudyPosts' : ActorMethod<[], Array<StudyPost>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeStudyPost' : ActorMethod<[bigint], undefined>,
  'registerUser' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendChatMessage' : ActorMethod<[string], undefined>,
  'updateDoubt' : ActorMethod<[bigint, string, string, string], undefined>,
  'updateProfile' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];